### ISSUE TITLE
Mod chests slots bug.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [pWn3d1337/Techguns#53] opened 2017-04-06 01:37 UTC
Shift-clicking any item from Reinforced or Weapon chest allows to move it to ammo slots.

![hwv4rg9](https://cloud.githubusercontent.com/assets/5104603/24733808/2d5b8f2e-1a7a-11e7-9775-0619a1df182c.png)
![93qrtxa](https://cloud.githubusercontent.com/assets/5104603/24733810/2ec1851c-1a7a-11e7-95ce-c8b929db02f0.png)

Mod version: Techguns.beta.1.2_Alphatest2

**Comment by pWn3d1337** [comment] 2017-04-06 06:56
I could not reproduce this bug. I will check again with the latest released build.

**Comment by YuRaNnNzZZ** [comment] 2017-04-06 07:23
[Here's the video of this bug](https://youtu.be/dNAP-fwY6do) reproduced on a clean install with latest public build from Curse.

**Comment by pWn3d1337** [comment] 2017-04-06 07:34
Ok, it's already fixed in the dev build. Thanks for the report.

**Closed** 2017-04-06 07:39 UTC
Labels: fixed
